### ISSUE TITLE
字体以及超链接问题

### ISSUE THREAD

**Issue by romise** [BHOSC/BUAAthesis#185]
在ubuntu16.04环境下，出现两个字体(time new man, stxingkai)不存在错误(本科毕设)，希望可以给予说明。同时，想问一下，目录的超链接为什么不设置为黑色呢？

**Comment by huxuan** [comment]
> 出现两个字体(time new man, stxingkai)不存在错误(本科毕设)

这两个字体是windows下面的字体，是学校模板的要求，既然已经用了Ubuntu，相信你应该知道怎么解决这个字体问题（Otherwise, please ask Google）。

> 目录的超链接为什么不设置为黑色呢？

默认是为了电子版方便阅读（实际黑白打印的时候影响也不大），而且这个只是一个设置而已，只要把文档的第一行`\documentclass[master,openright,twoside,color]{buaathesis}`中的`color`选项去掉就可以了。（文档第五章 [1] 有说明）

Please feel free to update if there is any further questions.

[1] https://github.com/BHOSC/BUAAthesis/blob/8d56eedeaa754cb7b4a717d23ad2fb80689a2f8a/data/chapter5-usage.tex#L52

**Comment by romise** [comment]
这个问题我已经解决了，但是仍然希望可以标注一下。

2016-11-13 15:05 GMT+08:00 Xuan Hu (Sean) <notifications@github.com>:

**Comment by huxuan** [comment]
Feel free to contribute with pull request. Close as problem resolved.
