### ISSUE TITLE
无法使用参考文献

### ISSUE THREAD

**Issue by lanyunzhu99** [BHOSC/BUAAthesis#256]
您好，我使用texlive2016编译，无法加入参考文献。编译您给的源文件也无法生成您的示例那样的参考文献，请问有解决的办法吗

**Comment by JosephPeng** [comment]
Due to your describration, I might suggest you to follow the compile the main.tex in the sequence of XeLatex -> BibTex -> XeLatex -> XeLatex. 
Thus, If there are any further question, refer to the doc file [https://github.com/BHOSC/BUAAthesis/blob/217bfe6b0f5d6f3c38845efbbda5feb6f014d97a/data/chapter5-usage.tex#L75](hrere)

**Comment by huxuan** [comment]
Besides, texlive 2016 is a too old version that is not guaranteed to work. Please consider to upgrade to the latest version first.

**Comment by sighingnow** [comment]
Close as it is a texlive related issue. The recent version should works as expected.
